name: ecdsa tests

on:
  pull_request:
    branches: master

jobs:
  # Run tests
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build docker image
        run: make build-no-cache

      - name: Run tests
        run: make ecdsa
